/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ciu;

import cci.ControladorPrincipal;

/**
 *
 * @author 2024122760199
 */
public class JanPrincipall extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JanPrincipall.class.getName());

    /**
     * Creates new form JanCadAlunoo
     */
    public JanPrincipall(ControladorPrincipal controlador) {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHome = new javax.swing.JMenu();
        jMenuCadastrar = new javax.swing.JMenu();
        jMenuItemAluno = new javax.swing.JMenuItem();
        jMenuItemCurso = new javax.swing.JMenuItem();
        jMenuItemProf = new javax.swing.JMenuItem();
        jMenuItemTurma = new javax.swing.JMenuItem();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItemAlunoList = new javax.swing.JMenuItem();
        jMenuItemProfList = new javax.swing.JMenuItem();
        jMenuItemGradeCurso = new javax.swing.JMenuItem();

        jMenuItem3.setText("jMenuItem3");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/painel.png"))); // NOI18N

        jMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Clip path group (2).png"))); // NOI18N
        jMenuHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuHome.setIconTextGap(0);
        jMenuHome.setMinimumSize(new java.awt.Dimension(30, 10));
        jMenuHome.setPreferredSize(new java.awt.Dimension(30, 10));
        jMenuBar1.add(jMenuHome);

        jMenuCadastrar.setText("Cadastrar");

        jMenuItemAluno.setText("Novo Aluno");
        jMenuItemAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlunoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemAluno);

        jMenuItemCurso.setText("Novo Curso");
        jMenuItemCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCursoActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemCurso);

        jMenuItemProf.setText("Novo Professor");
        jMenuItemProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProfActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemProf);

        jMenuItemTurma.setText("Nova Turma");
        jMenuItemTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTurmaActionPerformed(evt);
            }
        });
        jMenuCadastrar.add(jMenuItemTurma);

        jMenuBar1.add(jMenuCadastrar);

        jMenuConsultas.setText("Consultas");

        jMenuItemAlunoList.setText("Listar Alunos");
        jMenuItemAlunoList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlunoListActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemAlunoList);

        jMenuItemProfList.setText("Listar Professores");
        jMenuConsultas.add(jMenuItemProfList);

        jMenuItemGradeCurso.setText("Grade de Cursos");
        jMenuConsultas.add(jMenuItemGradeCurso);

        jMenuBar1.add(jMenuConsultas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlunoActionPerformed
        ControladorPrincipal.exibirJanCadAluno();
    }//GEN-LAST:event_jMenuItemAlunoActionPerformed

    private void jMenuItemCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCursoActionPerformed
        ControladorPrincipal.exibirJanCadCurso();
    }//GEN-LAST:event_jMenuItemCursoActionPerformed

    private void jMenuItemTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTurmaActionPerformed
        ControladorPrincipal.exibirJanCadTurma();
          }//GEN-LAST:event_jMenuItemTurmaActionPerformed

    private void jMenuItemAlunoListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlunoListActionPerformed
    }//GEN-LAST:event_jMenuItemAlunoListActionPerformed

    private void jMenuItemProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProfActionPerformed
 
        ControladorPrincipal.exibirJanCadProfessor();
    }//GEN-LAST:event_jMenuItemProfActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastrar;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenu jMenuHome;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemAluno;
    private javax.swing.JMenuItem jMenuItemAlunoList;
    private javax.swing.JMenuItem jMenuItemCurso;
    private javax.swing.JMenuItem jMenuItemGradeCurso;
    private javax.swing.JMenuItem jMenuItemProf;
    private javax.swing.JMenuItem jMenuItemProfList;
    private javax.swing.JMenuItem jMenuItemTurma;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables
}
